name: "Atividade CI/CD"

on:
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -h yarn

      - name: Install Dependecies
        run: yarn

      - name: Install Cypress
        run: yarn add cypress

      - name: Padronizacao de codigo
        run: yarn lint --write

      - name: Tests
        run: yarn run test

      - name: Generate Mochawesome Report
        run: |
          npx mochawesome-merge cypress/reports/*.json > mochawesome-report.json
          npx mochawesome-report-generator mochawesome-report.json --reportDir cypress/reports --quiet

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ./results
